db.collection("vagas").drop();
const viitra = await db
  .collection("empresas")
  .findOne({ "Razão Social": "Viitra inovações" });
const neurotech = await db
  .collection("empresas")
  .findOne({ "Razão Social": "Neurotech" });
const alpargatas = await db
  .collection("empresas")
  .findOne({ "Razão Social": "Alpargatas" });
const trackingTrade = await db
  .collection("empresas")
  .findOne({ "Razão Social": "Tracking trade" });
const mauriceia = await db
  .collection("empresas")
  .findOne({ "Razão Social": "Mauriceia Alimentos" });
const colombo = await db
  .collection("empresas")
  .findOne({ "Razão Social": "Confeitaria Colombo" });
await db.collection("vagas").insertMany([
  {
    _id: 1,
    titulo: "Desenvolvimento frontend",
    descrição:
      "Estamos em busca de um Desenvolvedor Frontend apaixonado por tecnologia e inovação para se juntar ao nosso time! Se você tem experiência com desenvolvimento de interfaces modernas, foco em usabilidade e performance, e gosta de trabalhar em equipe, essa vaga é para você!",
    empresa_id: viitra ? viitra._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação ou refeição",
      "Horário flexível",
      "Opção de trabalho remoto ou híbrido",
      "Auxílio para cursos e certificações",
      "Ambiente colaborativo e inovador",
    ],
    requisitos: [
      "Experiência com HTML, CSS e JavaScript",
      "Conhecimento avançado em React.js ou Vue.js",
      "Familiaridade com ferramentas de versionamento como Git",
      "Experiência com consumo de APIs REST e GraphQL",
      "Boas práticas de UI/UX",
      "Capacidade de trabalhar em equipe e boa comunicação",
      "Diferencial: experiência com Tailwind CSS e TypeScript",
    ],
    tipo: "CLT",
    salário: 4000.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-01"),
  },
  {
    _id: 2,
    titulo: "Cientista de Dados",
    descrição:
      "Estamos em busca de um Cientista de Dados talentoso para integrar nosso time! Se você tem paixão por análise de dados, modelagem preditiva e deseja trabalhar com grandes volumes de informação para gerar insights estratégicos, essa vaga é para você!",
    empresa_id: neurotech ? neurotech._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação ou refeição",
      "Horário flexível",
      "Opção de trabalho remoto ou híbrido",
      "Auxílio para cursos e certificações",
      "Ambiente colaborativo e inovador",
    ],
    requisitos: [
      "Experiência com Python e bibliotecas como Pandas, NumPy e Scikit-learn",
      "Conhecimento em SQL e manipulação de bancos de dados",
      "Experiência com Machine Learning e modelos preditivos",
      "Familiaridade com ferramentas de visualização de dados",
      "Conhecimento em engenharia de dados e ETL",
      "Diferencial: experiência com Big Data e frameworks como Spark",
    ],
    tipo: "PJ",
    salário: 6500.0,
    localização: "Recife",
    data_publicação: new Date("2025-03-20"),
  },
  {
    _id: 3,
    titulo: "Auxiliar de Serviços Gerais",
    descrição:
      "Estamos em busca de um Auxiliar de Serviços Gerais para atuar na limpeza e organização de nosso ambiente de trabalho. Se você é proativo, comprometido e gosta de trabalhar em equipe, essa vaga é para você!",
    empresa_id: alpargatas ? alpargatas._id : null,
    beneficios: [
      "Vale transporte",
      "Vale alimentação ou refeição",
      "Plano de saúde",
      "Seguro de vida",
      "Ambiente de trabalho organizado e acolhedor",
    ],
    requisitos: [
      "Experiência prévia na função (desejável)",
      "Conhecimento básico em produtos e equipamentos de limpeza",
      "Comprometimento com a organização e higiene do ambiente",
      "Boa disposição física",
      "Pontualidade e responsabilidade",
    ],
    tipo: "CLT",
    salário: 2000.0,
    localização: "Carpina",
    data_publicação: new Date("2025-03-25"),
  },
  {
    _id: 4,
    titulo: "Engenheiro de Software",
    descrição:
      "Estamos em busca de um Engenheiro de Software talentoso para integrar nosso time! Se você tem experiência no desenvolvimento de software escalável, arquitetura de sistemas e boas práticas de engenharia, essa vaga é para você!",
    empresa_id: trackingTrade ? trackingTrade._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação ou refeição",
      "Horário flexível",
      "Opção de trabalho remoto ou híbrido",
      "Auxílio para cursos e certificações",
      "Ambiente colaborativo e inovador",
    ],
    requisitos: [
      "Experiência com linguagens como Java, Python ou JavaScript",
      "Conhecimento em arquitetura de software e design patterns",
      "Experiência com bancos de dados relacionais e NoSQL",
      "Familiaridade com desenvolvimento de APIs REST e GraphQL",
      "Conhecimento em práticas ágeis (Scrum, Kanban)",
      "Experiência com ferramentas de CI/CD",
    ],
    tipo: "CLT",
    salário: 5000.0,
    localização: "São Paulo",
    data_publicação: new Date("2025-03-25"),
  },
  {
    _id: 5,
    titulo: "Cozinheiro(a)",
    descrição:
      "Estamos em busca de uma Cozinheira dedicada para integrar nossa equipe. A pessoa selecionada será responsável pela preparação de pratos com qualidade, seguindo as normas de higiene e segurança alimentar.",
    empresa_id: mauriceia ? mauriceia._id : null,
    beneficios: [
      "Salário competitivo",
      "Vale alimentação",
      "Vale transporte",
      "Assistência médica e odontológica",
      "Seguro de vida",
      "Possibilidade de crescimento profissional",
    ],
    requisitos: [
      "Experiência prévia como cozinheira",
      "Conhecimento das normas de higiene e segurança alimentar",
      "Capacidade de trabalhar em equipe e sob pressão",
      "Comprometimento e responsabilidade",
      "Disponibilidade para trabalhar em turnos ou horários flexíveis",
    ],
    tipo: "CLT",
    salário: 3200.0,
    localização: "Recife",
    data_publicação: new Date("2025-03-25"),
  },
  {
    _id: 6,
    titulo: "Motorista de Carga Viva",
    descrição:
      "Estamos em busca de um Motorista de Carga Viva para atuar no transporte de animais vivos de forma segura e responsável.",
    empresa_id: colombo ? colombo._id : null,
    beneficios: [
      "Salário competitivo",
      "Vale alimentação",
      "Vale transporte",
      "Assistência médica e odontológica",
      "Seguro de vida",
      "Possibilidade de crescimento profissional",
    ],
    requisitos: [
      "CNH categoria D ou E",
      "Experiência com transporte de carga viva",
      "Conhecimento das normas de transporte de animais",
      "Disponibilidade para viagens",
      "Comprometimento com o bem-estar animal",
    ],
    tipo: "CLT",
    salário: 3200.0,
    localização: "Recife",
    data_publicação: new Date("2025-03-25"),
  },
  {
    _id: 7,
    titulo: "Gerente de Projetos",
    descrição:
      "Estamos buscando um Gerente de Projetos experiente para liderar nossos projetos de desenvolvimento de software. Se você é organizado, comunicativo e apaixonado por tecnologia, essa vaga é para você!",
    empresa_id: viitra ? viitra._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação",
      "Horário flexível",
      "Trabalho remoto",
      "Treinamentos e certificações",
    ],
    requisitos: [
      "Experiência em gerenciamento de projetos de software",
      "Conhecimento em metodologias ágeis (Scrum, Kanban)",
      "Habilidade em comunicação e liderança",
      "Conhecimento em ferramentas de gerenciamento de projetos (Jira, Asana)",
    ],
    tipo: "CLT",
    salário: 7000.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-05"),
  },
  {
    _id: 8,
    titulo: "Assistente Administrativo",
    descrição:
      "Estamos em busca de um Assistente Administrativo para auxiliar em nossas rotinas administrativas. Se você é organizado, proativo e tem boa comunicação, essa vaga é para você!",
    empresa_id: alpargatas ? alpargatas._id : null,
    beneficios: [
      "Vale transporte",
      "Vale refeição",
      "Plano de saúde",
      "Seguro de vida",
    ],
    requisitos: [
      "Experiência em rotinas administrativas",
      "Conhecimento em pacote Office",
      "Boa comunicação e organização",
      "Ensino médio completo",
    ],
    tipo: "CLT",
    salário: 2500.0,
    localização: "Carpina",
    data_publicação: new Date("2025-04-06"),
  },
  {
    _id: 9,
    titulo: "Motorista Entregador",
    descrição:
      "Procuramos um Motorista Entregador para realizar entregas em nossa região. Se você é responsável, pontual e tem boa direção, essa vaga é para você!",
    empresa_id: mauriceia ? mauriceia._id : null,
    beneficios: [
      "Vale transporte",
      "Vale refeição",
      "Plano de saúde",
      "Seguro de vida",
    ],
    requisitos: [
      "CNH categoria B",
      "Experiência em entregas",
      "Conhecimento da região",
      "Boa direção e responsabilidade",
    ],
    tipo: "CLT",
    salário: 2800.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-07"),
  },
  {
    _id: 10,
    titulo: "Cozinheiro(a) Chefe",
    descrição:
      "Estamos procurando um Cozinheiro Chefe para liderar nossa equipe na cozinha. Se você é criativo, apaixonado por culinária e tem experiência em gestão de equipe, essa vaga é para você!",
    empresa_id: colombo ? colombo._id : null,
    beneficios: [
      "Salário competitivo",
      "Vale alimentação",
      "Plano de saúde",
      "Oportunidade de crescimento",
    ],
    requisitos: [
      "Experiência em cozinha profissional",
      "Conhecimento em gestão de equipe",
      "Criatividade e paixão por culinária",
      "Disponibilidade para trabalhar em horários flexíveis",
    ],
    tipo: "CLT",
    salário: 4500.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-08"),
  },
  {
    _id: 11,
    titulo: "Analista de Dados Júnior",
    descrição:
      "Estamos em busca de um Analista de Dados Júnior para integrar nosso time de ciência de dados. Se você é apaixonado por números e quer aprender a extrair insights valiosos, essa vaga é para você!",
    empresa_id: neurotech ? neurotech._id : null,
    beneficios: [
      "Plano de saúde",
      "Vale alimentação",
      "Horário flexível",
      "Treinamentos e cursos",
    ],
    requisitos: [
      "Conhecimento em SQL",
      "Familiaridade com Python e bibliotecas de análise de dados",
      "Boa comunicação e capacidade analítica",
      "Graduação em Estatística, Matemática, Ciência da Computação ou áreas afins",
    ],
    tipo: "PJ",
    salário: 3500.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-09"),
  },
  {
    _id: 12,
    titulo: "Desenvolvedor Backend",
    descrição:
      "Procuramos um Desenvolvedor Backend para construir e manter nossos sistemas. Se você tem experiência com desenvolvimento de APIs e bancos de dados, essa vaga é para você!",
    empresa_id: viitra ? viitra._id : null,
    beneficios: [
      "Plano de saúde",
      "Vale alimentação",
      "Horário flexível",
      "Trabalho remoto",
    ],
    requisitos: [
      "Experiência com Node.js, Python ou Java",
      "Conhecimento em bancos de dados relacionais e NoSQL",
      "Experiência com desenvolvimento de APIs REST",
      "Familiaridade com Docker e Kubernetes",
    ],
    tipo: "CLT",
    salário: 5500.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-10"),
  },
    {
    _id: 13,
    titulo: "Auxiliar de Limpeza",
    descrição:
      "Estamos procurando um Auxiliar de Limpeza para manter nosso ambiente limpo e organizado. Se você é proativo e responsável, essa vaga é para você!",
    empresa_id: alpargatas ? alpargatas._id : null,
    beneficios: [
      "Vale transporte",
      "Vale refeição",
      "Plano de saúde",
      "Seguro de vida",
    ],
    requisitos: [
      "Experiência em limpeza",
      "Conhecimento em produtos de limpeza",
      "Boa disposição física",
      "Responsabilidade e pontualidade",
    ],
    tipo: "CLT",
    salário: 2200.0,
    localização: "Carpina",
    data_publicação: new Date("2025-04-11"),
  },
    {
    _id: 14,
    titulo: "Analista de Projetos",
    descrição:
      "Buscamos um Analista de Projetos para auxiliar no planejamento e execução de nossos projetos. Se você é organizado e tem boa comunicação, essa vaga é para você!",
    empresa_id: trackingTrade ? trackingTrade._id : null,
    beneficios: [
      "Plano de saúde",
      "Vale alimentação",
      "Horário flexível",
      "Treinamentos e cursos",
    ],
    requisitos: [
      "Experiência em gerenciamento de projetos",
      "Conhecimento em metodologias ágeis",
      "Boa comunicação e organização",
      "Graduação em Administração, Engenharia ou áreas afins",
    ],
    tipo: "CLT",
    salário: 4800.0,
    localização: "São Paulo",
    data_publicação: new Date("2025-04-12"),
  },
    {
    _id: 15,
    titulo: "Ajudante de Cozinha",
    descrição:
      "Estamos procurando um Ajudante de Cozinha para auxiliar na preparação de pratos. Se você é rápido, organizado e apaixonado por culinária, essa vaga é para você!",
    empresa_id: colombo ? colombo._id : null,
    beneficios: [
      "Vale transporte",
      "Vale refeição",
      "Plano de saúde",
      "Oportunidade de crescimento",
    ],
    requisitos: [
      "Experiência em cozinha",
      "Conhecimento em higiene e segurança alimentar",
      "Boa disposição física",
      "Disponibilidade para trabalhar em horários flexíveis",
    ],
    tipo: "CLT",
    salário: 2500.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-13"),
  },
    {
    _id: 16,
    titulo: "Motorista de Caminhão",
    descrição:
      "Procuramos um Motorista de Caminhão para realizar o transporte de cargas em nossa região. Se você é responsável, pontual e tem boa direção, essa vaga é para você!",
    empresa_id: mauriceia ? mauriceia._id : null,
    beneficios: [
      "Vale transporte",
      "Vale refeição",
      "Plano de saúde",
      "Seguro de vida",
    ],
    requisitos: [
      "CNH categoria C ou D",
      "Experiência em transporte de cargas",
      "Conhecimento da região",
      "Boa direção e responsabilidade",
    ],
    tipo: "CLT",
    salário: 3500.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-14"),
  },
  {
    _id: 17,
    titulo: "Engenheiro de Alimentos Sênior",
    descrição:
      "Estamos em busca de um Engenheiro de Alimentos Sênior para liderar nossos projetos de desenvolvimento de novos produtos. Se você tem experiência em pesquisa e desenvolvimento, controle de qualidade e gestão de processos industriais, essa vaga é para você!",
    empresa_id: mauriceia ? mauriceia._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação",
      "Horário flexível",
      "Participação nos lucros",
      "Auxílio para cursos e certificações",
    ],
    requisitos: [
      "Experiência em pesquisa e desenvolvimento de produtos alimentícios",
      "Conhecimento em controle de qualidade e segurança alimentar",
      "Experiência em gestão de processos industriais",
      "Conhecimento em microbiologia de alimentos",
      "Habilidade em liderança e gestão de equipes",
      "Graduação em Engenharia de Alimentos",
    ],
    tipo: "CLT",
    salário: 8000.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-25"),
  },
  {
    _id: 18,
    titulo: "Médico Veterinário Sênior",
    descrição:
      "Estamos em busca de um Médico Veterinário Sênior para liderar nossa equipe de saúde animal. Se você tem experiência em diagnóstico e tratamento de doenças animais, cirurgia veterinária e manejo de grandes rebanhos, essa vaga é para você!",
    empresa_id: mauriceia ? mauriceia._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação",
      "Horário flexível",
      "Carro da empresa",
      "Auxílio para cursos e certificações",
    ],
    requisitos: [
      "Experiência em diagnóstico e tratamento de doenças animais",
      "Experiência em cirurgia veterinária",
      "Conhecimento em medicina preventiva e vacinação",
      "Habilidade em manejo e bem-estar animal",
      "Experiência em interpretação de exames laboratoriais",
      "Graduação em Medicina Veterinária",
    ],
    tipo: "CLT",
    salário: 7500.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-26"),
  },
  {
    _id: 19,
    titulo: "Atendente de Confeitaria",
    descrição:
      "Estamos em busca de um Atendente de Confeitaria apaixonado por encantar nossos clientes com um atendimento caloroso e acolhedor. Se você tem paixão por doces, bolos e outras delícias, e adora trabalhar em um ambiente alegre e saboroso, essa vaga é para você!",
    empresa_id: colombo ? colombo._id : null,
    beneficios: [
      "Vale transporte",
      "Vale refeição",
      "Plano de saúde",
      "Comissão por vendas",
      "Desconto em produtos da confeitaria",
    ],
    requisitos: [
      "Experiência em atendimento ao cliente",
      "Boa comunicação e simpatia",
      "Conhecimento sobre os produtos da confeitaria (desejável)",
      "Habilidade em trabalhar em equipe",
      "Ensino médio completo",
    ],
    tipo: "CLT",
    salário: 2200.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-27"),
  },
  {
    _id: 20,
    titulo: "Atendente de Suporte Técnico",
    descrição:
      "Estamos em busca de um Atendente de Suporte Técnico para auxiliar nossos clientes com dúvidas e problemas técnicos. Se você é paciente, comunicativo e tem conhecimento em tecnologia, essa vaga é para você!",
    empresa_id: neurotech ? neurotech._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação",
      "Horário flexível",
      "Trabalho remoto",
      "Auxílio para cursos e certificações",
    ],
    requisitos: [
      "Experiência em atendimento ao cliente",
      "Conhecimento em suporte técnico",
      "Habilidade em resolução de problemas",
      "Boa comunicação e paciência",
      "Conhecimento em informática",
    ],
    tipo: "CLT",
    salário: 3000.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-28"),
  },
  {
    _id: 21,
    titulo: "Designer de UI/UX",
    descrição:
      "Estamos procurando um Designer de UI/UX para criar interfaces incríveis para nossos produtos digitais. Se você é apaixonado por design e usabilidade, essa vaga é para você!",
    empresa_id: viitra ? viitra._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação",
      "Horário flexível",
      "Trabalho remoto",
      "Auxílio para cursos e certificações",
    ],
    requisitos: [
      "Experiência em design de interfaces web e mobile",
      "Conhecimento em ferramentas de design (Figma, Adobe XD)",
      "Habilidade em criar wireframes e protótipos",
      "Conhecimento em princípios de UI/UX",
      "Portfólio com projetos relevantes",
    ],
    tipo: "CLT",
    salário: 5000.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-29"),
  },
  {
    _id: 22,
    titulo: "Analista de Segurança da Informação",
    descrição:
      "Estamos em busca de um Analista de Segurança da Informação para proteger nossos sistemas e dados. Se você é apaixonado por segurança cibernética, essa vaga é para você!",
    empresa_id: viitra ? viitra._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação",
      "Horário flexível",
      "Trabalho remoto",
      "Auxílio para cursos e certificações",
    ],
    requisitos: [
      "Experiência em segurança da informação",
      "Conhecimento em normas e frameworks de segurança (ISO 27001, NIST)",
      "Habilidade em análise de vulnerabilidades e testes de penetração",
      "Conhecimento em firewalls, IDS/IPS e SIEM",
      "Certificações em segurança (CISSP, CEH) são diferenciais",
    ],
    tipo: "CLT",
    salário: 6000.0,
    localização: "Recife",
    data_publicação: new Date("2025-04-30"),
  },
  {
    _id: 23,
    titulo: "Engenheiro de Machine Learning",
    descrição:
      "Estamos procurando um Engenheiro de Machine Learning para desenvolver e implementar modelos de aprendizado de máquina. Se você é apaixonado por inteligência artificial, essa vaga é para você!",
    empresa_id: neurotech ? neurotech._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação",
      "Horário flexível",
      "Trabalho remoto",
      "Auxílio para cursos e certificações",
    ],
    requisitos: [
      "Experiência em desenvolvimento de modelos de machine learning",
      "Conhecimento em Python e bibliotecas como TensorFlow e PyTorch",
      "Habilidade em trabalhar com grandes volumes de dados",
      "Conhecimento em algoritmos de machine learning e deep learning",
      "Graduação em Ciência da Computação, Estatística ou áreas afins",
    ],
    tipo: "PJ",
    salário: 7500.0,
    localização: "Recife",
    data_publicação: new Date("2025-05-01"),
  },
  {
    _id: 24,
    titulo: "Analista de Dados Sênior",
    descrição:
      "Estamos em busca de um Analista de Dados Sênior para extrair insights valiosos de nossos dados. Se você é analítico e tem experiência em análise de dados, essa vaga é para você!",
    empresa_id: neurotech ? neurotech._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação",
      "Horário flexível",
      "Trabalho remoto",
      "Auxílio para cursos e certificações",
    ],
    requisitos: [
      "Experiência em análise de dados",
      "Conhecimento em SQL e ferramentas de visualização de dados (Tableau, Power BI)",
      "Habilidade em criar dashboards e relatórios",
      "Conhecimento em estatística e modelagem de dados",
      "Graduação em Estatística, Matemática, Ciência da Computação ou áreas afins",
    ],
    tipo: "PJ",
    salário: 6500.0,
    localização: "Recife",
    data_publicação: new Date("2025-05-02"),
  },
  {
    _id: 25,
    titulo: "Analista de Logística",
    descrição:
      "Estamos procurando um Analista de Logística para otimizar nossos processos de distribuição. Se você é organizado e tem conhecimento em logística, essa vaga é para você!",
    empresa_id: alpargatas ? alpargatas._id : null,
    beneficios: [
      "Vale transporte",
      "Vale refeição",
      "Plano de saúde",
      "Seguro de vida",
      "Desconto em produtos da empresa",
    ],
    requisitos: [
      "Experiência em logística e distribuição",
      "Conhecimento em sistemas de gestão de estoque (WMS)",
      "Habilidade em análise de dados e indicadores de desempenho",
      "Conhecimento em legislação de transporte",
      "Graduação em Logística, Administração ou áreas afins",
    ],
    tipo: "CLT",
    salário: 4500.0,
    localização: "Carpina",
    data_publicação: new Date("2025-05-03"),
  },
  {
    _id: 26,
    titulo: "Técnico de Segurança do Trabalho",
    descrição:
      "Estamos em busca de um Técnico de Segurança do Trabalho para garantir a segurança de nossos colaboradores. Se você é proativo e tem conhecimento em normas de segurança, essa vaga é para você!",
    empresa_id: alpargatas ? alpargatas._id : null,
    beneficios: [
      "Vale transporte",
      "Vale refeição",
      "Plano de saúde",
      "Seguro de vida",
    ],
    requisitos: [
      "Experiência em segurança do trabalho",
      "Conhecimento em normas regulamentadoras (NRs)",
      "Habilidade em realizar inspeções e treinamentos",
      "Conhecimento em primeiros socorros e combate a incêndios",
      "Curso técnico em Segurança do Trabalho",
    ],
    tipo: "CLT",
    salário: 3500.0,
    localização: "Carpina",
    data_publicação: new Date("2025-05-04"),
  },
  {
    _id: 27,
    titulo: "Analista de Sistemas Sênior",
    descrição:
      "Estamos procurando um Analista de Sistemas Sênior para liderar nossos projetos de desenvolvimento de software. Se você é experiente e tem conhecimento em arquitetura de sistemas, essa vaga é para você!",
    empresa_id: trackingTrade ? trackingTrade._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação",
      "Horário flexível",
      "Trabalho remoto",
      "Auxílio para cursos e certificações",
    ],
    requisitos: [
      "Experiência em análise e desenvolvimento de sistemas",
      "Conhecimento em arquitetura de software e design patterns",
      "Habilidade em liderança de equipes de desenvolvimento",
      "Conhecimento em bancos de dados relacionais e NoSQL",
      "Graduação em Ciência da Computação ou áreas afins",
    ],
    tipo: "CLT",
    salário: 7000.0,
    localização: "São Paulo",
    data_publicação: new Date("2025-05-05"),
  },
  {
    _id: 28,
    titulo: "Especialista em DevOps",
    descrição:
      "Estamos em busca de um Especialista em DevOps para automatizar nossos processos de desenvolvimento e implantação. Se você é apaixonado por automação e infraestrutura, essa vaga é para você!",
    empresa_id: trackingTrade ? trackingTrade._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação",
      "Horário flexível",
      "Trabalho remoto",
      "Auxílio para cursos e certificações",
    ],
    requisitos: [
      "Experiência em automação de infraestrutura (IaC)",
      "Conhecimento em ferramentas de CI/CD (Jenkins, GitLab CI)",
      "Habilidade em trabalhar com containers (Docker, Kubernetes)",
      "Conhecimento em cloud computing (AWS, Azure, GCP)",
      "Experiência em monitoramento de sistemas (Prometheus, Grafana)",
    ],
    tipo: "CLT",
    salário: 6500.0,
    localização: "São Paulo",
    data_publicação: new Date("2025-05-06"),
  },
  {
    _id: 29,
    titulo: "Analista de Marketing",
    descrição:
      "Estamos procurando um Analista de Marketing para desenvolver e implementar nossas estratégias de marketing. Se você é criativo e tem conhecimento em marketing digital, essa vaga é para você!",
    empresa_id: mauriceia ? mauriceia._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação",
      "Horário flexível",
      "Auxílio para cursos e certificações",
    ],
    requisitos: [
      "Experiência em marketing digital",
      "Conhecimento em SEO, SEM e mídias sociais",
      "Habilidade em criar conteúdo para web",
      "Conhecimento em ferramentas de análise de dados (Google Analytics)",
      "Graduação em Marketing, Publicidade ou áreas afins",
    ],
    tipo: "CLT",
    salário: 4800.0,
    localização: "Recife",
    data_publicação: new Date("2025-05-07"),
  },
  {
    _id: 30,
    titulo: "Supervisor de Produção",
    descrição:
      "Estamos em busca de um Supervisor de Produção para liderar nossa equipe de produção. Se você é organizado e tem experiência em gestão de equipes, essa vaga é para você!",
    empresa_id: mauriceia ? mauriceia._id : null,
    beneficios: [
      "Plano de saúde e odontológico",
      "Vale alimentação",
      "Horário flexível",
      "Auxílio para cursos e certificações",
    ],
    requisitos: [
      "Experiência em gestão de equipes de produção",
      "Conhecimento em processos de produção industrial",
      "Habilidade em liderança e comunicação",
      "Conhecimento em normas de segurança e qualidade",
      "Graduação em Engenharia de Produção ou áreas afins",
    ],
    tipo: "CLT",
    salário: 5500.0,
    localização: "Recife",
    data_publicação: new Date("2025-05-08"),
  },
  {
    _id: 41,
    titulo: "Gerente de Loja",
    descrição:
      "Estamos procurando um Gerente de Loja para liderar nossa equipe e garantir a excelência no atendimento aos nossos clientes. Se você é apaixonado por pessoas e tem experiência em gestão de equipes, essa vaga é para você!",
    empresa_id: colombo ? colombo._id : null,
    beneficios: [
      "Vale transporte",
      "Vale refeição",
      "Plano de saúde",
      "Comissão por vendas",
      "Desconto em produtos da confeitaria",
    ],
    requisitos: [
      "Experiência em gestão de equipes de vendas",
      "Habilidade em liderança e comunicação",
      "Conhecimento em técnicas de vendas e atendimento ao cliente",
      "Disponibilidade para trabalhar em horários flexíveis",
      "Ensino superior completo",
    ],
    tipo: "CLT",
    salário: 4000.0,
    localização: "Recife",
    data_publicação: new Date("2025-05-09"),
  },
  {
    _id: 42,
    titulo: "Confeiteiro(a) Sênior",
    descrição:
      "Estamos em busca de um Confeiteiro(a) Sênior para criar e preparar nossas deliciosas sobremesas. Se você é apaixonado por confeitaria e tem experiência na área, essa vaga é para você!",
    empresa_id: colombo ? colombo._id : null,
    beneficios: [
      "Vale transporte",
      "Vale refeição",
      "Plano de saúde",
      "Oportunidade de crescimento",
      "Desconto em produtos da confeitaria",
    ],
    requisitos: [
      "Experiência em confeitaria",
      "Conhecimento em técnicas de confeitaria",
      "Habilidade em criar e decorar bolos e doces",
      "Disponibilidade para trabalhar em horários flexíveis",
      "Curso técnico em Confeitaria (desejável)",
    ],
    tipo: "CLT",
    salário: 3800.0,
    localização: "Recife",
    data_publicação: new Date("2025-05-10"),
  },
]);